### ISSUE TITLE
Script doesn't seem to just work?

### ISSUE THREAD

**Issue by dfego** [tinfoil/openvpn_autoconfig#13]
Not sure if this is maintained, but I performed the following, have connected to my new VPN, and cannot get to the Internet with the given configurations:

1. Created a new Ubuntu 16.04 DigitalOcean server (NY3)
2. SSH'd and ran `wget https://raw.githubusercontent.com/tinfoil/openvpn_autoconfig/master/bin/openvpn.sh`
3. Ran `chmod +x openvpn.sh`
4. Ran `./openvpn.sh`
5. Rebooted (since openvpn wasn't running)
6. Ran `cat /etc/openvpn/client.ovpn` and pasted that into a file for my Windows OpenVPN GUI
7. Connected to the VPN successfully

With that in place, I can still SSH to my server (as expected) but can't get anywhere else on the 'net. I'm aware this isn't a "debug my VPN" help forum, but since the script is ideally a "just works" solution, I figured I'd reach out to see if anyone else has had any issues with it recently.

**Comment by bsedat** [comment]
I think we typically run this with 14.04 Ubuntu LTS. I suspect that some of the script would have trouble with the migration to systemd. Can you try running `systemctl status openvpn.service`?

**Comment by dfego** [comment]
Hmm, perhaps that's it. I just ran this on a 14.04 box and it works fine. That said, since you were nice enough to respond...

Right after I run the script:
```
# systemctl status openvpn.service
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-03-31 00:59:48 UTC; 8s ago
  Process: 2977 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 2977 (code=exited, status=0/SUCCESS)

Mar 31 00:59:48 vpn2 systemd[1]: Starting OpenVPN service...
Mar 31 00:59:48 vpn2 systemd[1]: Started OpenVPN service.
# pgrep -l vpn
#
```

At this stage, I can't connect to the VPN at all. After a reboot:
```
# systemctl status openvpn.service
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-03-31 01:03:05 UTC; 8s ago
  Process: 1454 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 1454 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/openvpn.service

Mar 31 01:03:05 vpn2 systemd[1]: Starting OpenVPN service...
Mar 31 01:03:05 vpn2 systemd[1]: Started OpenVPN service.
# pgrep -l vpn
1430 openvpn
1515 openvpn
```

When you mentioned this was typically done on 14.04, I destroyed the 16.04 box I was using and ran it successfully on 14.04. I'd like to clarify that I've done this process at least 5 times over the last few days. Of course this time, now that I've reached out for help... I can access the internet on this 16.04 VPN...

So... no bug?

**Comment by bsedat** [comment]
Ah, I believe the bug with 16.04 is that the script runs `service openvpn restart` once the new config is written. That should work fine in 14.04 with Upstart but we'd need to run `systemctl restart openvpn.service` in 16.04 to have the same behavior.
